# Generated by Django 3.0.2 on 2020-07-26 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='club_id',
            field=models.CharField(default='abc', max_length=50),
            preserve_default=False,
        ),
    ]
